theme: jekyll-theme-slate 
title: this is a personal profile about boguer!💗💗
description: here you can find a really different me!
plugins: 
    - jemoji 
url: "https://boguer31.github.io/" 
markdown: kramdown
